import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { fallbackCatalog } from '../data/fallback.js';
import { api } from '../lib/api.js';

export default function ProfileSetup({ setUser, setProfile }) {
  const navigate = useNavigate();
  const [catalog, setCatalog] = useState(fallbackCatalog);
  const [form, setForm] = useState({
    fullName: 'Demo Student',
    email: 'student@studypulse.ai',
    password: 'password123',
    phone: '9876543210',
    college: 'StudyPulse Engineering College',
    academicYear: '3rd Year',
    course: 'btech',
    department: 'cse',
    subject: 'java',
    resumeName: '',
    github: 'https://github.com/demo-student',
    linkedin: 'https://linkedin.com/in/demo-student',
    portfolio: 'https://portfolio.example.com'
  });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    api.catalog().then(setCatalog).catch(() => setCatalog(fallbackCatalog));
  }, []);

  const courses = catalog?.catalog?.courses || [];
  const selectedCourse = courses.find((course) => course.id === form.course) || courses[0];
  const departments = selectedCourse?.departments || [];
  const selectedDepartment = departments.find((dept) => dept.id === form.department) || departments[0];
  const subjectOptions = selectedDepartment?.subjects || ['java', 'dbms', 'dsa', 'webdev'];
  const subjects = catalog?.subjects || [];

  useEffect(() => {
    if (!courses.length) return;
    const course = courses.find((item) => item.id === form.course) || courses[0];
    const department = course.departments.find((item) => item.id === form.department) || course.departments[0];
    const subject = department?.subjects?.includes(form.subject) ? form.subject : department?.subjects?.[0];
    if (course.id !== form.course || department?.id !== form.department || subject !== form.subject) {
      setForm((prev) => ({ ...prev, course: course.id, department: department?.id || '', subject: subject || '' }));
    }
  }, [catalog, courses, form.course, form.department, form.subject]);

  const update = (field, value) => {
    setForm((prev) => {
      if (field === 'course') {
        const nextCourse = courses.find((course) => course.id === value);
        const nextDepartment = nextCourse?.departments?.[0];
        return { ...prev, course: value, department: nextDepartment?.id || '', subject: nextDepartment?.subjects?.[0] || '' };
      }
      if (field === 'department') {
        const nextDepartment = departments.find((dept) => dept.id === value);
        return { ...prev, department: value, subject: nextDepartment?.subjects?.[0] || '' };
      }
      return { ...prev, [field]: value };
    });
  };

  const submit = (event) => {
    event.preventDefault();
    setError('');
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) {
      setError('Enter a valid email address.');
      return;
    }
    if (form.password.length < 8) {
      setError('Password must be at least 8 characters.');
      return;
    }
    setSubmitting(true);
    const user = { fullName: form.fullName, email: form.email, provider: 'email-password-demo', authenticated: true };
    const profile = { ...form, selectedSubjectOnly: form.subject, completedSubjects: [], activeSubjects: [form.subject] };
    setUser(user);
    setProfile(profile);
    localStorage.setItem('sp-user', JSON.stringify(user));
    localStorage.setItem('sp-profile', JSON.stringify(profile));
    navigate('/analysis');
  };

  return (
    <section className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
      <form onSubmit={submit} className="glass rounded-xl p-6 shadow-glow">
        <p className="text-sm uppercase tracking-[0.2em] text-cyan-200">Authentication and profile setup</p>
        <h2 className="mt-2 text-3xl font-semibold">Mandatory student profile</h2>
        <p className="mt-2 text-slate-300">The adaptive system is generated by the selected subject only. Course and department organize the academic hierarchy.</p>
        <div className="mt-5 grid gap-3 sm:grid-cols-2">
          <button type="button" className="rounded-lg border border-cyan-300/30 bg-cyan-300/10 px-4 py-3 text-sm font-semibold text-cyan-50">Continue with Google</button>
          <button type="button" className="rounded-lg border border-white/10 bg-white/10 px-4 py-3 text-sm font-semibold text-white">Email and password login</button>
        </div>

        <div className="mt-6 grid gap-4 md:grid-cols-2">
          {[
            ['fullName', 'Full Name'],
            ['email', 'Email'],
            ['password', 'Password'],
            ['phone', 'Phone Number'],
            ['college', 'College Name'],
            ['academicYear', 'Academic Year']
          ].map(([field, label]) => (
            <label key={field} className="space-y-2 text-sm text-slate-300">{label}
              <input type={field === 'password' ? 'password' : field === 'email' ? 'email' : 'text'} value={form[field]} onChange={(e) => update(field, e.target.value)} autoComplete={field === 'password' ? 'current-password' : field === 'email' ? 'email' : 'on'} minLength={field === 'password' ? 8 : undefined} className="w-full rounded-lg border border-white/10 bg-slate-950/70 px-4 py-3 text-white outline-none focus:border-cyan-300" required />
            </label>
          ))}
        </div>

        <div className="mt-5 grid gap-4 md:grid-cols-3">
          <label className="space-y-2 text-sm text-slate-300">Course
            <select value={form.course} onChange={(e) => update('course', e.target.value)} className="w-full rounded-lg border border-white/10 bg-slate-950 px-4 py-3 text-white">
              {courses.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}
            </select>
          </label>
          <label className="space-y-2 text-sm text-slate-300">Department
            <select value={form.department} onChange={(e) => update('department', e.target.value)} className="w-full rounded-lg border border-white/10 bg-slate-950 px-4 py-3 text-white">
              {departments.map((dept) => <option key={dept.id} value={dept.id}>{dept.name}</option>)}
            </select>
          </label>
          <label className="space-y-2 text-sm text-slate-300">Subject
            <select value={form.subject} onChange={(e) => update('subject', e.target.value)} className="w-full rounded-lg border border-white/10 bg-slate-950 px-4 py-3 text-white">
              {subjectOptions.map((subjectId) => {
                const subject = subjects.find((item) => item.id === subjectId);
                return <option key={subjectId} value={subjectId}>{subject?.name || subjectId}</option>;
              })}
            </select>
          </label>
        </div>

        <div className="mt-5 grid gap-4 md:grid-cols-2">
          <label className="space-y-2 text-sm text-slate-300">Resume Upload Optional
            <input type="file" onChange={(e) => update('resumeName', e.target.files?.[0]?.name || '')} className="w-full rounded-lg border border-white/10 bg-slate-950/70 px-4 py-3 text-white file:mr-3 file:rounded-full file:border-0 file:bg-cyan-400 file:px-3 file:py-1 file:text-slate-950" />
          </label>
          <label className="space-y-2 text-sm text-slate-300">GitHub Profile Link
            <input type="url" required value={form.github} onChange={(e) => update('github', e.target.value)} className="w-full rounded-lg border border-white/10 bg-slate-950/70 px-4 py-3 text-white outline-none" />
          </label>
          <label className="space-y-2 text-sm text-slate-300">LinkedIn Profile Link
            <input type="url" required value={form.linkedin} onChange={(e) => update('linkedin', e.target.value)} className="w-full rounded-lg border border-white/10 bg-slate-950/70 px-4 py-3 text-white outline-none" />
          </label>
          <label className="space-y-2 text-sm text-slate-300">Portfolio Link
            <input type="url" value={form.portfolio} onChange={(e) => update('portfolio', e.target.value)} className="w-full rounded-lg border border-white/10 bg-slate-950/70 px-4 py-3 text-white outline-none" />
          </label>
        </div>

        {error && <p className="mt-5 rounded-lg bg-red-500/10 px-4 py-3 text-sm text-red-100 ring-1 ring-red-300/20">{error}</p>}
        <button disabled={submitting} className="mt-6 w-full rounded-full bg-cyan-400 px-6 py-3 font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-60">
          {submitting ? 'Saving profile...' : 'Save profile and start mandatory AI analysis'}
        </button>
      </form>

      <aside className="glass rounded-xl p-6 shadow-glow">
        <h3 className="text-2xl font-semibold">Strict project flow</h3>
        <div className="mt-5 space-y-3 text-sm text-slate-300">
          <div className="rounded-lg bg-white/10 p-4">1. Login with email/password or Google demo.</div>
          <div className="rounded-lg bg-white/10 p-4">2. Select Course to Department to Subject.</div>
          <div className="rounded-lg bg-white/10 p-4">3. Upload career links and resume signal.</div>
          <div className="rounded-lg bg-white/10 p-4">4. Roadmap is blocked until analysis test is completed.</div>
        </div>
      </aside>
    </section>
  );
}
